---
- name: Push authorized SSH keys for root
  copy:
    src: /root/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    mode: 0644

- name: Install nginx
  include_tasks:
    file: setup-nginx.yml

- name: Install PHP.
  include_tasks:
    file: setup-php.yml
  vars:
    php_version: "{{ php_version_item }}"
  loop: "{{ php_versions }}"
  loop_control:
    loop_var: php_version_item

- name: Setup system wide default PHP version.
  lineinfile:
    path: /etc/profile.d/system-module-defaults.sh
    regexp: '^module load php[0-9][0-9]*$'
    line: 'module load php{{php_versions[0] | regex_replace("[.]", "") }}'
    owner: root
    group: root
    mode: 0644

- include_role:
    name: geerlingguy.composer

- name: Setup mongodb
  import_tasks: "setup-mongodb.yml"

- name: Install packages from standard repos not already installed.
  yum:
    name:
      - indent
      - redis
      - sassc
    state: present

# Apparently nodejs.org is still signing with SHA1, which is now
# disabled. To undo this, set it back to 'DEFAULT'
- name: Enable SHA1 package signing for nodejs
  command: update-crypto-policies --set DEFAULT:SHA1

- include_role:
    name: geerlingguy.nodejs

- name: Setup MEDUSA user
  include_tasks: setup-medusa-user.yml

- name: Setup MEDUSA code
  include_tasks: setup-medusa.yml
