---
- name: Push authorized SSH keys for root
  copy:
    src: /root/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    mode: 0644

- name: Install nginx
  include_tasks:
    file: setup-nginx.yml

- name: Install PHP.
  include_tasks:
    file: install-php.yml
  vars:
    php_version: "{{ php_version_item }}"
  loop: "{{ php_versions }}"
  loop_control:
    loop_var: php_version_item

- name: Setup mongodb
  import_tasks: "setup-mongodb.yml"

# - name: Setup xdebug
#   import_tasks: "setup-xdebug.yml"

- name: Install packages from standard repos
  yum:
    name:
      - redis
      - ImageMagick
      - pkgconfig
      - sassc
    state: present

# - name: Install non-prompting PHP modules
#   pear:
#     name: "{{item}}"
#     state: present
#   with_items:
#     - pecl/imagick
#     - pecl/mongodb
#
# - name: Install redis
#   shell: printf "no\nyes\n" | pecl install pecl/redis
#
# - include_role:
#     name: geerlingguy.composer
#
# - include_role:
#     name: geerlingguy.nodejs
#
# - name: Configure php-fpm
#   ini_file:
#     path: /etc/php-fpm.d/www.conf
#     section: "{{item.section}}"
#     option: "{{item.option}}"
#     value: "{{item.value}}"
#   with_items:
#     - { section: "www", option: "listen", value: "/var/run/php-fpm/php-fpm.sock" }
#     - { section: "www", option: "listen.owner", value: "nobody" }
#     - { section: "www", option: "listen.group", value: "nobody" }
#     - { section: "www", option: "listen.mode", value: "0660" }
#
# - name: Clone MEDUSA
#   git:
#     repo: 'https://github.com/TRMN/medusa.git'
#     dest: /var/www/medusa
#
# - name: Create MEDUSA environment
#   command: cp .env.example .env
#   args:
#     creates: .env
#     chdir: /var/www/medusa
#
# - name: Install PHP dependencies
#   command: composer install
#   args:
#     chdir: /var/www/medusa
#
# - name: Install node dependencies
#   command: npm install
#   args:
#     chdir: /var/www/medusa
#
# - name: Do a node audit fix
#   command: npm audit fix
#   args:
#     chdir: /var/www/medusa
#
# - name: Install MEDUSA server file
#   command: cp server_configurations/nginx/medusa.dev /etc/nginx/servers/conf.d/medusa.conf
#   args:
#     creates: /etc/nginx/servers/conf.d/medusa.conf
