---
  - name: Create groups for virtual host type/role.
    group_by:
      key: virt_{{ ansible_virtualization_type }}_{{ ansible_virtualization_role }}
    when:
      "ansible_facts['virtualization_type'] is defined and ansible_facts['virtualization_type'] not in ['', 'NA']"

  - name: Create group based on OS family/version for RHEL/CentOS
    group_by:
      key: el{{ ansible_distribution_major_version }}_{{ ansible_architecture }}
      parents:
      - el{{ ansible_distribution_major_version }}
    when:
      ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] != 'Fedora'
