---
# tasks file for install-mongodb on RedHat distributions.

- name: "Add repository for MongoDB"
  yum_repository:
    name: "mongodb-org-{{mongodb_version}}"
    description: MongoDB Repository
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{mongodb_version}}/x86_64/"
    gpgcheck: true
    enabled: true
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{mongodb_version}}.asc"
  when:
    - mongodb_version is defined
    - mongodb_version in [6.0, 7.0, 8.0]

- name: "Install MongoDB"
  yum:
    name: "{{mongodb_packages}}"
    state: installed
  notify: Restart mongod
  when:
    - mongodb_version is defined
    - mongodb_version in [6.0, 7.0, 8.0]
