---
- name: Include PHP {{php_version}} vars
  include_vars:
    file: "php{{ php_version }}-vars.yml"

- name: Include PHP version module
  include_role:
    name: geerlingguy.php-versions

- name: Do the PHP {{php_version}} install
  include_role:
    name: geerlingguy.php

#
# Setup system wide default PHP version. This file must follow modules.sh in
# /etc/profile.d alphabetically so that modules.sh is sourced by /etc/profile
# first to provide the modules command.
#
- name: Check to see if system-module-defaults exists.
  stat:
    path: /etc/profile.d/system-module-defaults.sh
  register: st

- name: Create system-module-defaults since it does not exist
  file:
    path: /etc/profile.d/system-module-defaults.sh
    owner: root
    group: root
    mode: 0644
    state: touch

- name: Setup system wide default PHP version.
  lineinfile:
    path: /etc/profile.d/system-module-defaults.sh
    regexp: '^module load php[0-9][0-9]*$'
    line: 'module load php{{php_version | regex_replace("[.]", "") }}'

- name: Update pecl channel
  command: 'pecl channel-update pecl.php.net'

- name: Install non-prompting PHP modules
  pear:
    name: "{{item}}"
    state: present
  with_items:
    - pecl/mongodb

#- name: Install redis
#  shell: printf "no\nyes\n" | pecl install pecl/redis

- name: Clear system wide default PHP version.
  lineinfile:
    path: /etc/profile.d/system-module-defaults.sh
    regexp: '^module load php[0-9][0-9]*$'
    line: 'module load php{{php_version | regex_replace("[.]", "") }}'
    state: absent

- name: Disable the PHP {{ php_version }} module
  command: "dnf -y module disable php:remi-{{ php_version }}"
