---
# handlers file for ansible-roles-medusa

- name: Restart mongod
  service:
    name: mongod
    state: "{{mongod_state}}"
    enabled: "{{mongod_enabled}}"
  when:
    - mongod_enabled
    - mongodb_version is defined
    - mongodb_version in ['3.2', '3.4', '3.6', '4.0']

- name: Reload firewalld
  command: firewall-cmd --reload

- name: Restart nginx
  service:
    name: nginx
    state: restarted
